config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/house_members/vote_info', to: 'house_vote_info#index'
  get '/senators/vote_info', to: 'senator_vote_info#index'
  resources :house_members, only: [:show]
  resources :senators, only: [:show]
  root to: 'home#index'
  get '/representatives/:state_abbreviation', to: 'representatives#index'
  post '/senators/:id/favorites', to: 'senator_favorites#create'
  delete '/senators/:id/favorites', to: 'senator_favorites#destroy'
  delete '/house_members/:id/favorites', to: 'house_members_favorites#destroy'
  post '/house_members/:id/favorites', to: 'house_members_favorites#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'dashboard#show'
  get '/bills', to: 'bills#index'
  get '/comparison', to: 'comparison#index'

  post '/results/:congress_id', to: 'results#create'
  get '/results/:congress_id', to: 'results#show', as: 'results'
end

app/models/house_member.rb
class HouseMember < ApplicationRecord
  has_many :house_favorites, dependent: :destroy
  has_many :users, through: :house_member_favorites
  def self.by_state(state_abbrev, order = 'asc', limit = 400)
    self.where(state: "#{state_abbrev}")
        .order(last_name: "#{order}")
        .limit(limit)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.includes?(congress_id)
    self.exists?(congress_id: "#{congress_id}")
  end

  def self.house_favorites_for_user(id)
    HouseMember.joins(house_favorites:[:user]).where('house_favorites.comparison_score IS NOT NULL AND house_favorites.user_id = ?', id)
  end

  def compare_votes_with_user(user_votes)
    yes_hash = {}
    no_hash = {}
    user_votes.each do |bill_id, vote|
      bill = Bill.find_by(bill_id: bill_id)
      roll_call = bill.house_bill_vote.roll_call
      session = bill.house_bill_vote.session
      if vote == 'yes'
        yes_hash["#{bill_id}"] = SinatraService.new.get_member_votes(congress_id, roll_call, "house", session)["data"]["#{roll_call}"]
      elsif vote == 'no'
        no_hash["#{bill_id}"] = SinatraService.new.get_member_votes(congress_id, roll_call, "house", session)["data"]["#{roll_call}"]
      end
    end
    matching_bills = []
    not_matching_bills = []
    yes_hash.each do |bill_id, house_member_vote|
      bill_id = Bill.find_by(bill_id: bill_id).id
      if house_member_vote == 'Yes'
        matching_bills << bill_id
      elsif house_member_vote == 'No'
        not_matching_bills << bill_id
      end
    end
    no_hash.each do |bill_id, house_member_vote|
      bill_id = Bill.find_by(bill_id: bill_id).id
      if house_member_vote == 'No'
        matching_bills << bill_id
      elsif house_member_vote == 'Yes'
        not_matching_bills << bill_id
      end
    end
    number_compared = matching_bills.length + not_matching_bills.length.to_f
    comparison_score = (matching_bills.length / number_compared) * 100
    {comparison_score: comparison_score, matching_bills: matching_bills, not_matching_bills: not_matching_bills}
  end
end

app/controllers/house_members_controller.rb
class HouseMembersController < ApplicationController

  def show
    id = house_member_params[:id]
    @rep = HouseMember.find(id)
    @other_reps = HouseMember.by_state(@rep.state)
    @senators = Senator.by_state(@rep.state)
    @state = ::States[@rep.state]
    @image = SinatraService.new.get_image(@rep.congress_id)
  end

  private

  def house_member_params
    params.permit(:id)
  end
end

app/views/house_members/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Representative Show Page</title>
</head>
<div class="sidenav" style="margin-top: 15px;">
  <p>Representatives in <%= @state %></p>
  <% @other_reps.each do |rep| %>
    <p><%= link_to "#{rep.first_name} #{rep.last_name}", house_member_path(rep.id) %></p>
  <% end %>
</div>

<div class="senate-sidenav">
  <p>Senators in <%= @state %></p>
  <% @senators.each do |senator| %>
  <p><%= link_to "#{senator.first_name} #{senator.last_name}", senator_path(senator.id)%></p>
  <% end %>
</div>
<% if @rep.twitter_account %>
<div class="right-side-nav">
  <a class="twitter-timeline" href="https://twitter.com/<%= @rep.twitter_account %>?ref_src=twsrc%5Etfw">Twitter</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
<div class="col-lg-3 fixed-image">
  <%= image_tag(@image, class:'img-fluid rounded mb-4 mb-lg-0', id: 'rep-image') %>
  <br>
  <br>
  <a class="btn btn-primary" href="/bills?name=<%= @rep.full_name %>&congress_id=<%= @rep.congress_id %>">Compare Positions</a>
</div>
<% end %>
  <body>
    <section class='rep-info'>
    <div class="row align-items-center my-5">
      <!-- /.col-lg-8 -->
      <div class="col-lg-5">
        <h1 class='rep-name'><%= @rep.first_name %> <%= @rep.last_name %></h1>
        <h4 class='rep-district'><%= "Representative from:" %><br/>
          <%= ::States[@rep.state] + "'s " %>
          <% if @rep.at_large %>At-Large District
          <% else %><%= @rep.district.ordinalize + " District" %>
          <% end %> </h4>
        <% if current_user && current_user.house_members.include?(@rep)%>
          <%= button_to "Remove from Favorites", "/house_members/#{@rep.id}/favorites", method: :delete %>
        <% elsif current_user && !current_user.house_members.include?(@rep)%>
          <%= button_to "Add to Favorites" , "/house_members/#{@rep.id}/favorites", method: :post%>
        <% else %>
           <p class="login-message">Log in to add this representative to your dashboard</p>
        <% end %>
        <br class='rep-dob'>Date of Birth: <%= Date.parse(@rep.dob).strftime('%B %-d, %Y') %>
        <br class='rep-gender'>Gender: <%= @rep.gender %>
        <br class='rep-party'>Party: <%= @rep.party %>
        <% if @rep.leadership_role %>
          <br class='rep-leadership'>Leadership Role: <%= @rep.leadership_role %>
        <% end %>
        <% if @rep.cook_pvi %>
          <br class='rep-cook_pvi'>District's Cook PVI: <%= @rep.cook_pvi %>
          <span class="tooltip-data tool-format">?</span>
          <div id="popup">The Cook PVI is a measure of a district's partisanship. An even district has roughly the same number of Democrats and Republicans. The higher the number D or R, the more Democratic or Republican the district is.</div>
        <% end %>
        <% if @rep.dw_nominate %>
          <br class='rep-dw_nominate'>DW NOMINATE Score: <%= @rep.dw_nominate %>
          <span class="dw-data tool-format">?</span>
          <div id="popup" class="dw-popup">The DW-Nominate is a measure of a representative’s partisanship. The closer to -1 a representative is, the more liberal their positions are - the closer they are to +1, the more conservative their positions are.</div>
        <% end %>
        <% if @rep.office %>
          <br class='rep-office'>D.C. Office: <%= @rep.office %>
        <% end %>
        <% if @rep.phone %>
          <br class='rep-phone'>Office Phone: <%= @rep.phone %>
        <% end %>
        <% if @rep.url %>
          <br class='rep-url'>Official Website: <%= link_to nil, @rep.url %>
        <% end %>
        <% if @rep.contact_form %>
          <br class='rep-contact'><%= link_to "Contact #{@rep.first_name} #{@rep.last_name}", @rep.url %>
        <% end %>
        <% if @rep.facebook_account %>
          <br class='rep-facebook'>Facebook: <%= link_to @rep.facebook_account, "http://www.facebook.com/#{@rep.facebook_account}" %>
        <% end %>
        <% if @rep.twitter_account %>
          <br class='rep-twitter'>Twitter: <%= link_to @rep.twitter_account, "http://www.twitter.com/#{@rep.twitter_account}" %>
        <% end %>
        <% if @rep.total_votes %>
          <br class='rep-total_votes'>Total Votes: <%= @rep.total_votes %>
          <br><a class="btn btn-sm btn-primary" href="/house_members/vote_info" role="button">Click to see more</a>
        <% end %>
        <% if @rep.missed_votes %>
          <br class='rep-missed_votes'>Missed Votes: <%= @rep.missed_votes %>
        <% end %>
        <% if @rep.missed_votes_percentage %>
          <br class='rep-missed_votes_percentage'>Missed Votes Percentage: <%= @rep.missed_votes_percentage %> %
        <% end %>
        <% if @rep.votes_with_percentage %>
          <br class='rep-votes_with_percentage'>Votes with Party Percentage: <%= @rep.votes_with_percentage %> %
        <% end %>
        <% if @rep.votes_without_party_percentage %>
          <br class='rep-votes_without_party_percentage'>Votes Against Party Percentage: <%= @rep.votes_without_party_percentage %> %
        <% end %>
      </div>
      <!-- /.col-md-4 -->
    </div>
    </section>
</body>

</html>
<script>
var e = document.querySelector('.tooltip-data');
e.onmouseover = function() {
  document.getElementById('popup').style.display = 'flex';
}
e.onmouseout = function() {
  document.getElementById('popup').style.display = 'none';
}
var q = document.querySelector('.dw-data');
if(q !== null){
  q.onmouseover = function() {
    document.querySelector('.dw-popup').style.display = 'block';
  }
  q.onmouseout = function() {
    document.querySelector('.dw-popup').style.display = 'none';
  }
}
</script>